import { Confession, Profile, Comment } from '@/types';

export const INITIAL_CONFESSIONS: Confession[] = [
  {
    id: 'confession-1',
    user_id: 'user-101',
    anon_handle_snapshot: 'SpicyAvocado_842',
    title: 'I leaked our company budget spreadsheet to force a raise',
    body: 'My boss claimed there was zero budget for engineering raises this year. So I casually left the Q3 executive bonus spreadsheet on the communal office printer. Everyone saw it. 48 hours later, our entire team got a 22% cost-of-living bump. Best mistake of my career.',
    category: 'work',
    tea_score: 98,
    tea_temperature: '💀 NUCLEAR',
    ai_verdict: 'Robin Hood of corporate Tech 💀 FBI couldn\'t force a confession out of me like this. Legendary behavior.',
    ai_vibe_tag: 'Villain Origin Story',
    reaction_counts: { tea: 240, spicy: 310, dead: 180, yikes: 12, red_flag: 4, iconic: 420 },
    upvotes: 890,
    downvotes: 14,
    comment_count: 42,
    city: 'Bengaluru',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'confession-2',
    user_id: 'user-102',
    anon_handle_snapshot: 'ChaosGoblin_193',
    title: 'Attended my ex\'s wedding as a hired secret saxophone soloist',
    body: 'My ex told me I lacked artistic vision when we broke up 3 years ago. Her wedding planner posted an urgent gig for a jazz musician last month. I took the contract under a pseudonym, wore a mask, and performed the most tragic solo during their first dance. She didn\'t recognize me until the final song.',
    category: 'relationship',
    tea_score: 91,
    tea_temperature: '🌶️ Spicy',
    ai_verdict: 'The pettiness is so immaculate it belongs in the Louvre 🎷 You wrote the curriculum for petty arc.',
    ai_vibe_tag: 'Main Character Moment',
    reaction_counts: { tea: 195, spicy: 280, dead: 210, yikes: 8, red_flag: 15, iconic: 340 },
    upvotes: 670,
    downvotes: 9,
    comment_count: 28,
    city: 'Mumbai',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'confession-3',
    user_id: 'user-103',
    anon_handle_snapshot: 'MidnightTea_702',
    title: 'I substituted my roommate\'s expensive matcha with spirulina powder',
    body: 'He kept taking my artisanal coffee beans without asking and calling me a pleb. So for 3 weeks I replaced his imported ceremonial grade matcha tin with 100% pure organic spirulina algae powder. He told everyone his skin never looked clearer.',
    category: 'petty',
    tea_score: 76,
    tea_temperature: '🔥 Hot',
    ai_verdict: 'Accidental holistic health guru moment 🍵 Toxic yet surprisingly nutritional.',
    ai_vibe_tag: 'Cope Arc',
    reaction_counts: { tea: 110, spicy: 94, dead: 150, yikes: 5, red_flag: 2, iconic: 130 },
    upvotes: 410,
    downvotes: 6,
    comment_count: 19,
    city: 'Delhi',
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'confession-4',
    user_id: 'user-104',
    anon_handle_snapshot: 'VelvetViper_505',
    title: 'Faked an allergy to avoid my mother-in-law\'s weekly mystery casserole',
    body: 'I paid a local clinic testing lab to mock up a fake mild eggplant intolerance report just so I didn\'t have to eat her soggy eggplant parmigiana every Sunday. My wife still doesn\'t know.',
    category: 'family',
    tea_score: 64,
    tea_temperature: '🔥 Hot',
    ai_verdict: 'Forging medical documents to avoid bad cooking is high-level survival instinct 😭',
    ai_vibe_tag: 'Therapy Needed',
    reaction_counts: { tea: 85, spicy: 60, dead: 120, yikes: 18, red_flag: 3, iconic: 90 },
    upvotes: 295,
    downvotes: 12,
    comment_count: 14,
    city: 'Pune',
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'confession-5',
    user_id: 'user-105',
    anon_handle_snapshot: 'ShadowRaven_911',
    title: 'I submitted my final university project written 90% by custom automation',
    body: 'I built a python script that parsed past top grade dissertations, generated full LaTeX tables, and cited obscure 1980s academic papers. The professor called it "masterful research methodology" and wants to publish it.',
    category: 'school',
    tea_score: 84,
    tea_temperature: '🌶️ Spicy',
    ai_verdict: 'If you publish it, the script gets the co-author credit 🤖 Work smarter, not harder.',
    ai_vibe_tag: 'Sigma Grindset',
    reaction_counts: { tea: 160, spicy: 210, dead: 90, yikes: 4, red_flag: 6, iconic: 310 },
    upvotes: 520,
    downvotes: 8,
    comment_count: 23,
    city: 'Hyderabad',
    created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
  }
];

export const INITIAL_PROFILE: Profile = {
  id: 'user-current-me',
  anon_handle: 'DramaLlama_77',
  email: 'anonymous@spillboard.app',
  karma: 340,
  streak_days: 4,
  last_active_date: new Date().toISOString().split('T')[0],
  badges: ['first_spill', 'tea_master'],
  handle_rerolls_today: 0,
  is_premium: false,
  created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
};

export const INITIAL_COMMENTS: Record<string, Comment[]> = {
  'confession-1': [
    {
      id: 'comm-1',
      confession_id: 'confession-1',
      user_id: 'user-201',
      anon_handle_snapshot: 'ToxicKitten_33',
      body: 'Bro single-handedly solved corporate wealth redistribution 👑',
      upvotes: 45,
      created_at: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'comm-2',
      confession_id: 'confession-1',
      user_id: 'user-202',
      anon_handle_snapshot: 'GhostlyPanther_89',
      body: 'Did the boss ever find out who left it on the printer??',
      upvotes: 21,
      created_at: new Date(Date.now() - 1800000).toISOString(),
    }
  ]
};
